//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlZDataService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/CtrlZDataService")]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime createdDateField;
        
        private CtrlZDataService.EmgData[] emgListField;
        
        private string gestureField;
        
        private System.Guid idField;
        
        private CtrlZDataService.MotionData[] motionListField;
        
        private string usernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createdDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CtrlZDataService.EmgData[] emgList
        {
            get
            {
                return this.emgListField;
            }
            set
            {
                this.emgListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gesture
        {
            get
            {
                return this.gestureField;
            }
            set
            {
                this.gestureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CtrlZDataService.MotionData[] motionList
        {
            get
            {
                return this.motionListField;
            }
            set
            {
                this.motionListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmgData", Namespace="http://schemas.datacontract.org/2004/07/CtrlZDataService")]
    public partial class EmgData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime createdDateField;
        
        private int emg1Field;
        
        private int emg2Field;
        
        private int emg3Field;
        
        private int emg4Field;
        
        private int emg5Field;
        
        private int emg6Field;
        
        private int emg7Field;
        
        private int emg8Field;
        
        private int orderReceivedField;
        
        private long timestampField;
        
        private System.Guid transactionIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createdDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int emg1
        {
            get
            {
                return this.emg1Field;
            }
            set
            {
                this.emg1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int emg2
        {
            get
            {
                return this.emg2Field;
            }
            set
            {
                this.emg2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int emg3
        {
            get
            {
                return this.emg3Field;
            }
            set
            {
                this.emg3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int emg4
        {
            get
            {
                return this.emg4Field;
            }
            set
            {
                this.emg4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int emg5
        {
            get
            {
                return this.emg5Field;
            }
            set
            {
                this.emg5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int emg6
        {
            get
            {
                return this.emg6Field;
            }
            set
            {
                this.emg6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int emg7
        {
            get
            {
                return this.emg7Field;
            }
            set
            {
                this.emg7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int emg8
        {
            get
            {
                return this.emg8Field;
            }
            set
            {
                this.emg8Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderReceived
        {
            get
            {
                return this.orderReceivedField;
            }
            set
            {
                this.orderReceivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MotionData", Namespace="http://schemas.datacontract.org/2004/07/CtrlZDataService")]
    public partial class MotionData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double accelXField;
        
        private double accelYField;
        
        private double accelZField;
        
        private System.DateTime createdDateField;
        
        private double gyroXField;
        
        private double gyroYField;
        
        private double gyroZField;
        
        private int orderReceivedField;
        
        private double orientationPitchField;
        
        private double orientationRollField;
        
        private double orientationWField;
        
        private double orientationXField;
        
        private double orientationYField;
        
        private double orientationYawField;
        
        private double orientationZField;
        
        private long timestampField;
        
        private System.Guid transactionIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double accelX
        {
            get
            {
                return this.accelXField;
            }
            set
            {
                this.accelXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double accelY
        {
            get
            {
                return this.accelYField;
            }
            set
            {
                this.accelYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double accelZ
        {
            get
            {
                return this.accelZField;
            }
            set
            {
                this.accelZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createdDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double gyroX
        {
            get
            {
                return this.gyroXField;
            }
            set
            {
                this.gyroXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double gyroY
        {
            get
            {
                return this.gyroYField;
            }
            set
            {
                this.gyroYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double gyroZ
        {
            get
            {
                return this.gyroZField;
            }
            set
            {
                this.gyroZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderReceived
        {
            get
            {
                return this.orderReceivedField;
            }
            set
            {
                this.orderReceivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double orientationPitch
        {
            get
            {
                return this.orientationPitchField;
            }
            set
            {
                this.orientationPitchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double orientationRoll
        {
            get
            {
                return this.orientationRollField;
            }
            set
            {
                this.orientationRollField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double orientationW
        {
            get
            {
                return this.orientationWField;
            }
            set
            {
                this.orientationWField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double orientationX
        {
            get
            {
                return this.orientationXField;
            }
            set
            {
                this.orientationXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double orientationY
        {
            get
            {
                return this.orientationYField;
            }
            set
            {
                this.orientationYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double orientationYaw
        {
            get
            {
                return this.orientationYawField;
            }
            set
            {
                this.orientationYawField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double orientationZ
        {
            get
            {
                return this.orientationZField;
            }
            set
            {
                this.orientationZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICtrlZService")]
public interface ICtrlZService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtrlZService/AddTransaction", ReplyAction="http://tempuri.org/ICtrlZService/AddTransactionResponse")]
    bool AddTransaction(CtrlZDataService.Transaction t1);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICtrlZServiceChannel : ICtrlZService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CtrlZServiceClient : System.ServiceModel.ClientBase<ICtrlZService>, ICtrlZService
{
    
    public CtrlZServiceClient()
    {
    }
    
    public CtrlZServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CtrlZServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CtrlZServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CtrlZServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool AddTransaction(CtrlZDataService.Transaction t1)
    {
        return base.Channel.AddTransaction(t1);
    }
}
